### ISSUE TITLE
Questions when running "blender_notebook install --blender-exec="/snap/bin/blender""

### ISSUE THREAD

**Issue by WangYixuan12** [cheng-chi/blender_notebook#2]
I follow the installation instructions in README, but when I run `blender_notebook install --blender-exec="/snap/bin/blender"`, I got the return 
```
Traceback (most recent call last):
  File "/home/deformtrack/local/src/miniconda2/bin/blender_notebook", line 5, in <module>
    from blender_notebook.installer import main
ModuleNotFoundError: No module named 'blender_notebook'
```
I use miniconda in my computer, and the system is Ubuntu 18.04.4 LTS. My Python version is 3.7.7. Would you like to help me with that?

**Comment by WangYixuan12** [comment]
Oh I found the command should be `blender-notebook install --blender-exec="/snap/bin/blender"`. I think maybe it is better to modify README or make it consistent with the repo title.

**Comment by cheng-chi** [comment]
@WangYixuan12 Sounds like a bug, both should work. I will investigate.
